spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: promotion_route
          uri: lb://promotion-service
          predicates:
            - Path=/api/promotion/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: tripartite_route
          uri: lb://tripartite-service
          predicates:
            - Path=/api/tripartite/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

#        低优先级
        - id: admin_route
          uri: lb://dangdang-mall-bff
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}




#前端项目 /api


server:
  port: 8095




