server:
  port: 10001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dangdang_smt?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: promotion-service

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
